Implement and Test Matrix and Vector Classes
GigaKekes/spbu-python-course pull request #1
Opened 2024-10-01 14:23 UTC by GigaKekes

This pull request introduces two new classes, Matrix and Vector, that support basic mathematical operations. Both classes offer functionality that integrates well with NumPy and Python's standard indexing.

## 1. Matrix Class Implementation:

- `__init__`: Initializes the matrix using a 2D iterable.
- `__add__`: Adds two matrices.
- `__matmul__`: Multiplies two matrices.
- `T`: Returns the transpose of the matrix.
- `__getitem__`: Allows access to matrix elements using mat[i, j].
- `__repr__ `and `__str__`: Provides string representations of the matrix for easy reading and debugging.
- `__array__`: Enables interaction with NumPy methods directly on the matrix object.
- `data`: Property to access the underlying matrix.

## 2. Vector Class Implementation:

- `__init__`: Initializes the vector using an iterable.
- `__array__`: Allows the Vector object to be treated as a NumPy array directly.
- `__getitem__`: Enables access to elements using vector indexing.
- `__len__`: Returns the length (dimension) of the vector.
- `__mul__`: Calculates the dot product of two vectors.
- `__xor__`: Computes the angle (in radians) between two vectors.
- `norm`: Calculates the Euclidean norm (magnitude) of the vector.

## Tests

- Matrix Class:
- - Unit tests for matrix addition, multiplication, transpose, item access, and string representations.
- - Tests for invalid operations (e.g., shape mismatches during matrix multiplication).
- Vector Class:
- - Unit tests for vector operations such as dot product, angle calculation, norm, and element access.
- - Compatibility tests with NumPy array operations using __array__.

2024-10-01 19:44 UTC, Krekep requested changes
В целом хорошо, но необходимы исправления.
По поводу typehints у `object` --- либо сузить область допустимых значений, либо посмотреть в сторону collections.abc.Iterable, но я с этим не работал, так что не уверен, что получится.

2024-10-01 19:44 UTC, Krekep commented on project/vector_matrix_operations/Matrix.py
> +    def __init__(self, object):
У `object` отсутствует typehint

2024-10-01 19:44 UTC, Krekep commented on project/vector_matrix_operations/Vector.py
> +    def __init__(self, object):
У `object` отсутствует typehint

2024-10-01 19:44 UTC, Krekep commented on tests/test_vector_matrix_operations/test_matrix_operations.py
> +        mat1 @ mat2
Не хватает теста на умножение не квадратных матриц

2024-10-02 07:23 UTC, GigaKekes commented
### Added
- Typehint for parameter `object` in classes `Vector` и `Matrix`
- Python version in `.yml`  files were updated to 3.12.2 so `X | Y` syntax for unions can be used
### Tests
- Test on rectangular matrix multiplication  `test_matrix_multiplication_non_square`

2024-10-02 08:35 UTC, Krekep approved these changes
Зачтено

2024-10-02 08:44 UTC, merged