Климовский Дмитрий. Task №3
GigaKekes/spbu-python-course pull request #3
Opened 2024-10-17 12:34 UTC by GigaKekes

# Задача 3. Генераторы

* **Дедлайн**: 17.10.2024, 23:59
* Полный балл: 5

## Задача

- [x] Написать генераторное выражение для четырехмерного набора векторов [RGBA](https://en.wikipedia.org/wiki/RGBA_color_model) модели, где прозрачность принимает только чётные значения. Реализуйте функцию, возвращаю `i` элемент этого набора. Каждый цвет может принимать значения от 0 до 255 включительно, прозрачность может принимать значения от 0 до 100 включительно.
- [x] Реализовать функцию-генератор последовательности простых чисел. Обернуть её в декоратор, возвращающий `k`-е простое число (нумерация с единицы).
- [x] Добавить тесты покрывающие реализованную функциональность. Тесты должны использовать либо декоратор pytest.fixture, либо pytest.parametrize.

2024-10-18 18:07 UTC, Krekep requested changes
Необходимы исправления

2024-10-18 18:07 UTC, Krekep commented on project/generators/primes.py
> +        i += 1
С одной стороны это решение работает быстрее наивного, но с другой стороны оно требует дополнительной (и не константой) памяти.
Суть этого генератора в том, что он может сгенерировать бесконечную последовательность простых чисел, но добавив в него массив, в котором хранятся найденный простые, Вы ограничили размер последовательности.
Перепишите его без использования массива с простыми числами

2024-10-18 18:07 UTC, Krekep commented on project/generators/primes.py
> +    return prime
Это не декоратор для генератора простых чисел.
Это просто функция, которая хранит инстанс генератора и обращается к нему

2024-10-18 18:07 UTC, Krekep commented on project/generators/rgba.py
> +                    yield (r, g, b, a)
Это функция-генератор, а генераторное выражение это что-то в духе
```
(i for i in range(10))
```

2024-10-18 18:07 UTC, Krekep commented on project/generators/rgba.py
> +                    yield (r, g, b, a)
Формально Вы правы, но перепишите с использованием `if` для демонстрации того, что Вы это умеете

2024-10-20 11:21 UTC, GigaKekes commented
# Изменения
* Переписан `rgba_generator`. теперь он возвращает `generator comprehension` с использованием `if`.
* Написан декоратор для простых чисел.
* Написан генератор для простых чисел, работающий за O(1) по памяти.

2024-10-20 11:38 UTC, Krekep requested changes
Необходимы исправления

2024-10-20 11:38 UTC, Krekep commented on tests/test_generators/test_primes.py
> +        decorated_gen(-1)  # k is less than or equal to 0
Это стоит сделать через `parametrize`

2024-10-20 11:38 UTC, Krekep commented on tests/test_generators/test_primes.py
> +    assert next(prime_gen) == 13
Почему не использовать напрямую `prime_generator`?

2024-10-20 11:38 UTC, Krekep commented on tests/test_generators/test_primes.py
> +    assert decorated_gen(k) == expected
Этот тест не проверит того, что генератор несколько подряд запросов корректно обрабатывает, т.к. `pytest.mark.parametrize` на каждый test case заново запускает функцию

2024-10-20 12:11 UTC, Krekep approved these changes
Зачтено

2024-10-20 12:15 UTC, merged