Климовский Дмитрий. Task №4
GigaKekes/spbu-python-course pull request #4
Opened 2024-10-20 17:59 UTC by GigaKekes

# Задача 4. Пул потоков

* **Дедлайн**: 24.10.2024, 23:59
* Полный балл: 10

## Задача

- [x] Реализовать паттерн "пул потоков".
  - [x] Число потоков задаётся константой в классе пула или параметром конструктора.
  - [x] У каждого потока есть два состояния: ожидание задачи, выполнение задачи.
  - [x] Задача --- некая функция проводящая вычисления и возвращающая результат.
  - [x] Добавление задачи осуществляется с помощью метода `enqueue(task)`
  - [x] При добавлении задачи, если в пуле есть ожидающий поток, то он должен приступить к её выполнению. Иначе задача будет ожидать исполнения, пока не освободится какой-нибудь поток.
  - [x] Метод `dispose` должен завершать работу потоков. Уже запущенные задачи не прерываются, но новые задачи не принимаются на исполнение потоками из пула.
  - [x] Ограничения:
    - Разрешено использовать только пакет threading
    - Для каждого базового сценария должен быть написан несложный тест
    - Также должен быть написан тест, проверяющий, что в пуле действительно не менее `n` потоков
  - [x] Допущения:
    - Использование класса для реализации пула потоков необязательно
- [x] **(Доп., +2 балла)** С помощью `concurrent.futures` реализовать параллельное вычисление суммы полного декартового произведения множества целых чисел

2024-10-21 08:30 UTC, Krekep requested changes
Необходимы исправления

2024-10-21 08:30 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +from queue import Queue
Этот класс реализует в себе методы для работы с потоками. Из пакетов для работы с многопоточностью по условию задачи разрешён только `threading`

2024-10-21 08:30 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +        return result.result()
Вынесите в отдельный файл

2024-10-21 08:30 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +    with ThreadPoolExecutor() as executor:
Чем обоснован выбор `ThreadPoolExecutor` для этой задачи?

2024-10-21 08:30 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +        result = executor.submit(sum, (sum(t) for t in cartesian_product))
Вы отправляете одну задачу, которая будет выполняться одним потоком, нет?

2024-10-21 08:30 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +    pool.dispose()
Лучше проверять через `threading.active_count()`

2024-10-21 08:30 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +    [(33, [{22}, {11}]), (20, [{1, 2}, {3, 4}]), (84, [{1, 2}, {3, 4}, {5, 6}])],
В целом в условии подразумевалось множество чисел `A` и его декартово произведение на само себя, т.е. `A^2`. Это не замечание, просто уточнение, что Вы можете упростить тесты.

2024-10-21 08:30 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +def test_parallel_cartesian_sum(expected_sum, list_of_sets):
Круто, что корректно складываются числа, но хочется ещё посмотреть на сравнительное время работы

2024-10-22 08:21 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +def test_parallel_cartesian_sum(expected_sum, list_of_sets):
Ладно, скорее всего я был неправ, давая такое задание. Для более тяжёлых функций, чем `sum` задание имело бы смысл, но в с учётом того, что `sum` использует сишную реализацию, оверхед на копирование массивов между процессами и их синхронизацию сильно больше, чем выигрыш от их использования в такой простой задаче. Так что окей, можете не добавлять такой тест. Либо можете добавить более тяжёловесную функцию (добавить, к примеру косинусы, синусы, корни или, к примеру, сортировку сделать) и показать, что с процессами она будет быстрее
Также можете почитать [этот тред](https://www.reddit.com/r/Python/comments/5tfm64/multiprocessing_parallel_sum_slower_than_serial/) и [вот этот](https://stackoverflow.com/questions/42074501/python-concurrent-futures-processpoolexecutor-performance-of-submit-vs-map)

2024-10-23 11:39 UTC, GigaKekes commented on tests/test_thread_pool/test_thread_pool.py
> +    pool.dispose()
Понял, поменял.

2024-10-23 11:42 UTC, GigaKekes commented on project/thread_pool/thread_pool.py
> +    with ThreadPoolExecutor() as executor:
Я разобрался и перешел на реализацию с `ProcessPoolExecutor`. Он должен реализовывать настоящее распараллеливание.

2024-10-23 11:42 UTC, GigaKekes commented on project/thread_pool/thread_pool.py
> +        result = executor.submit(sum, (sum(t) for t in cartesian_product))
Понял. Переделал

2024-10-23 11:50 UTC, GigaKekes commented
# Изменения
* [x] Декомпозировал `parallel_cartesian_sum`. Вынес в файлик соответствующий.
* [x] Перешел с `Queue` на `List` с локами и эвентами
* [x] Перешел с  `ThreadPoolExecutor` на `ProcessPoolExecutor`. Добавил тест на пустой `set`. 
* [x] Переделал тест `test_num_threads`. Реализовал через `threading.active_count()`

2024-10-24 08:48 UTC, Krekep approved these changes
Зачтено

2024-10-24 08:48 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +        pool.enqueue(lambda i=i: simple_task(results, i))
Как будто эту лямбду можно проще написать

2024-10-24 20:06 UTC, merged