Климовский Дмитрий. Task №5
GigaKekes/spbu-python-course pull request #5
Opened 2024-10-30 13:13 UTC by GigaKekes

# Задача 5. Игра

* **Дедлайн**: 31.10.2024, 23:59
* Полный балл: 13

## Задача

- [x] Реализовать одну из игр в списке ниже. Вариант определяется как длина Вашего ФИО по модулю 2 плюс 1
  1. [рулетка](https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%BB%D0%B5%D1%82%D0%BA%D0%B0)
  2. [блэкджек](https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D1%8D%D0%BA%D0%B4%D0%B6%D0%B5%D0%BA)
- Пример выбора варианта
  - len(Алимов Павел Геннадьевич) = 6 + 5 + 11 = 22
  - 22 % 2 = 0
  - 0 + 1 = 1 -> вариант 1
-------------------
  - Требования:
    - [x] Должно быть как минимум три различных стратегии игры ботов
    - [x] Должны быть методы, показывающие текущее состояние игры
    - [x] На каждую сущность должен быть свой класс
  - Ограничения:
    - Игра ведётся либо до победы одного/нескольких участников, либо до заданного количества шагов
  - Допущения:
    - Реализовывать Игрока необязательно. Достаточно того, что в игре будут участвовать только боты
    - Графический интерфейс необязателен. Информацию достаточно выводить в консоль
  - Проверка:
    - Будет проверяться декомпозиция на классы
    - Тесты должны отображать
      - Что состояние игры меняется с течением времени
      - Работоспособность методов влияющих на состояние игры
      - Может быть что-то ещё, тестов много не бывает
    - Надо добавить пример работы игры с выводом информации о состоянии в каждом раунде. Для примеров лучше создать отдельную папку `examples`
- [x] **(Доп., +5 балла)** Для реализованной игры построить [UML диаграмму классов](https://en.wikipedia.org/wiki/Class_diagram)
- [x] **(Доп., +5 балла)** С помощью метаклассов добавить стратегию бота и поменять правила игры (к примеру, количество полей или условия победы)

2024-11-01 08:09 UTC, Krekep requested changes
В целом хорошо, но необходимы исправления

2024-11-01 08:09 UTC, Krekep commented on project/game/RouletteWheel.py
> +        }
Стоит оформить это не как словарь, а как класс

2024-11-01 08:09 UTC, Krekep commented on project/game/docs/UML.drawio.png
1. Отношение к метаклассам должно быть "зависимость"
2. Видимость, к примеру, `strategy` у `Bot` должна быть публичной? Проверьте все поля и методы на соответствие принципу инкапсуляции

2024-11-01 08:09 UTC, Krekep commented on project/game/main.py
> +    )
Добавьте более сложную стратегию, чем просто случайный выбор.

2024-11-01 08:09 UTC, Krekep commented on project/game/main.py
Этот файл не должен находиться в исходниках. Он скорее должен находиться в примерах

2024-11-02 09:56 UTC, GigaKekes commented on project/game/RouletteWheel.py
> +        }
Исправил.

2024-11-02 09:56 UTC, GigaKekes commented on project/game/main.py
Перенес в examples

2024-11-02 10:09 UTC, GigaKekes commented on project/game/main.py
> +    )
добавил стратегию с 2 случайными выборами.

2024-11-02 10:19 UTC, GigaKekes commented on project/game/docs/UML.drawio.png
переделал

2024-11-02 10:22 UTC, GigaKekes commented
# Исправления
* main.py перенесен в examples
* проработана инкапсуляция (немного)
* изменил UML диаграмму
* Добавил датакласс `RouletteNumber`

2024-11-06 12:03 UTC, Krekep requested changes
Необходимы исправления

2024-11-06 12:03 UTC, Krekep commented on project/game/Croupier.py
> +                ):
Магические константы это [антипаттерн в программировании](https://en.wikipedia.org/wiki/Magic_number_(programming)). У Вас в качестве магических констант выступают типы ставок и цвета (мб ещё что-то, пока не весь код просмотрел), перепишите код без них

2024-11-06 12:03 UTC, Krekep commented on project/game/RouletteWheel.py
> +        }
Вместо словаря стоит создать класс/перечисление/именованный кортеж для результата вращения колеса

2024-11-06 12:03 UTC, Krekep commented on project/game/docs/UML.drawio.png
`play_round` и `balance` должны быть публичными? В остальном вроде нормально

2024-11-06 22:23 UTC, GigaKekes commented on project/game/Croupier.py
> +                ):
Убрал. Теперь бот получает только 2x на ставку.

2024-11-06 22:24 UTC, GigaKekes commented on project/game/RouletteWheel.py
> +        }
заменил на именованный кортеж

2024-11-06 22:38 UTC, GigaKekes commented on project/game/docs/UML.drawio.png
изменил на private и protected соответственно

2024-11-07 11:32 UTC, Krekep requested changes
Вы не избавились от магических констант и это третья проверка, так что незачёт

2024-11-07 11:32 UTC, Krekep commented on tests/test_game/test_bot.py
> +    return {"type": "number", "choice": 2 * random.randint(0, 18)}
Вы так и не избавились от магических словарей и констант

2024-11-07 11:32 UTC, Krekep commented on tests/test_game/test_croupier.py
> +    return SpinResult(number=1, color="Red", parity="Odd", third=1, row=3, half=1)
Вместо строк стоит использовать перечисления/классы/именованные кортежи

2024-11-07 11:32 UTC, Krekep commented on project/game/Croupier.py
> +                winnings = bet_amount * 2
Верните разный размер выплат вознаграждения, в зависимости от типа ставки

2024-11-15 11:26 UTC, closed without merging